In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sentence=['the glass of milk',
          'the glass of juice',
          'the cup of tea',
          'I am a good boy',
          'I am a good developer',
          'understand the meaning of words',
          'My posters are good',
]

In [3]:
# define the vocabulary size
voc_size=10000

In [4]:
## One hot representation
onehot_representation=[one_hot(word,voc_size )for word in sentence]
onehot_representation

[[4239, 7058, 1470, 4534],
 [4239, 7058, 1470, 6048],
 [4239, 8739, 1470, 6472],
 [3574, 4437, 9490, 2479, 6163],
 [3574, 4437, 9490, 2479, 2466],
 [9927, 4239, 9627, 1470, 4941],
 [1275, 2603, 8312, 2479]]

In [5]:
## Word Embedding representation
import numpy as np
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
sent_length=8
embedded_doc=pad_sequences(onehot_representation,padding='pre',maxlen=sent_length)
print(embedded_doc)

[[   0    0    0    0 4239 7058 1470 4534]
 [   0    0    0    0 4239 7058 1470 6048]
 [   0    0    0    0 4239 8739 1470 6472]
 [   0    0    0 3574 4437 9490 2479 6163]
 [   0    0    0 3574 4437 9490 2479 2466]
 [   0    0    0 9927 4239 9627 1470 4941]
 [   0    0    0    0 1275 2603 8312 2479]]


In [7]:
## Feature Representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim))
model.build(input_shape=(None, sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step


array([[[ 2.38179453e-02, -6.66054338e-03, -4.36853170e-02,
          1.15174875e-02, -2.19585430e-02, -4.12145853e-02,
         -4.48595174e-02,  3.08378823e-02, -2.39902381e-02,
         -4.40965556e-02],
        [ 2.38179453e-02, -6.66054338e-03, -4.36853170e-02,
          1.15174875e-02, -2.19585430e-02, -4.12145853e-02,
         -4.48595174e-02,  3.08378823e-02, -2.39902381e-02,
         -4.40965556e-02],
        [ 2.38179453e-02, -6.66054338e-03, -4.36853170e-02,
          1.15174875e-02, -2.19585430e-02, -4.12145853e-02,
         -4.48595174e-02,  3.08378823e-02, -2.39902381e-02,
         -4.40965556e-02],
        [ 2.38179453e-02, -6.66054338e-03, -4.36853170e-02,
          1.15174875e-02, -2.19585430e-02, -4.12145853e-02,
         -4.48595174e-02,  3.08378823e-02, -2.39902381e-02,
         -4.40965556e-02],
        [-2.48579625e-02,  3.39303873e-02, -4.99288924e-02,
          9.93993133e-03,  7.75586814e-04,  1.24586113e-02,
          1.57238580e-02, -3.06302197e-02,  1.350155

In [15]:
embedded_doc[0]

array([   0,    0,    0,    0, 4239, 7058, 1470, 4534], dtype=int32)